# Generated by Django 4.2.5 on 2023-10-04 08:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('from_date', models.DateField(max_length=255, null=True)),
                ('until_date', models.DateField(max_length=255, null=True)),
                ('description', models.TextField(max_length=255)),
                ('show_in_cv', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('LANGUAGE_SKILL', 'Language skills'), ('IT_SKILL', 'IT & Software skills'), ('OTHER_SKILL', 'Other skills')], max_length=255)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0, message='Lowest possible skill level is 0'), django.core.validators.MaxValueValidator(5, message='Highest possible skill level is 5')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
