# Generated by Django 4.2.5 on 2023-10-02 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=255)),
                ("website_links", models.URLField(blank=True)),
                ("profile_photo", models.ImageField(upload_to="images/")),
                ("phone_number", models.PositiveIntegerField()),
                ("zip_code", models.PositiveIntegerField()),
                ("street", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WorkingExperience",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('from_date', models.DateField(max_length=255, null=True)),
                ('until_date', models.DateField(max_length=255, null=True)),
                ('description', models.TextField(max_length=255)),
                ('show_in_cv', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
